# Use postgres/example user/password credentials
version: '3.6'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - blog

  
  blog:
    image: username/blog
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
      - POSTGRES_HOST=db:5432
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - blog
  
networks:
  blog:
    name: blog