CREATE SCHEMA blog AUTHORIZATION blog;
GRANT USAGE ON SCHEMA blog TO blog;
CREATE TABLE IF NOT EXISTS blog.blog (
   ID         SERIAL NOT NULL PRIMARY KEY,
   BODY       TEXT   NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
